# Generated by Django 5.1.4 on 2024-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('importance', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=7)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
