# Generated by Django 5.1.4 on 2024-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stock_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
