# Generated by Django 5.1.4 on 2024-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
